### ISSUE TITLE
GET /animals/

### ISSUE THREAD

**Issue by smarbos** [smarbos/adopteitor-feathers#1]
# /Animals:
Current URL: http://www.adoptaungalgoenargentina.com:8080/Animal/

I think maybe we should rename and use plural terms for endpoints, /animals/ sound better to me. If we choose to change the URL, we must update the client also.

## Tasks:
- Create GET endpoint
- [ ] /animals/ should return all animals in the DB
- [ ] Always return results with pagination.
- [ ] We need to look at the query params and check for any of this values in order to filter the data the endpoint responds.

## Query parameters:
- galgo_filter:
- - If galgo_filter is "a", returns "adults"
- - If galgo_filter is "c", returns "puppys"
- - if galgo_filter is "h", returns "males",
- - if galgo_filter is "m", returms "females"
- galgo_id: Fetch animals by property "id"
- galgo_genero: Fetch animals by property "genero"
- galgo_etapa: Fetch animals by property "etapa"

## Returns:
The endpoint should return an array of animals

[Original implementatio](https://github.com/smarbos/adopteitor-server/blob/master/views.py#L25)

**Comment by anabellaspinelli** [comment]
I say yes to:
- Changing entities to plural (`/animals/`) (even if it means changing the FE)
- Having all key names in english in the backend (and figuring out how to handle localization in the FE)
- Filter by any attribute, in a verbose manner (example: `?gender=male&ageGroup=puppies...` etc)

Lovely issue btw 😘
